name: mymorning
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0-255.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_reactive_ble: ^5.0.3
  location_permissions: ^4.0.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  expandable_page_view: ^1.0.17
  floating_bottom_navigation_bar: ^1.5.2
  flutter_time_picker_spinner: ^2.0.0
  flutter_spinner_picker:
    path: ./flutter_spinner_picker
  numberpicker: ^2.1.1
  flutter_advanced_switch: ^3.0.1
  fluttertoast: ^8.1.1
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.12
  change_app_package_name: ^1.1.0

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf

# Splash screen & app icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  background_image: "assets/images/splash_screen.png"
# flutter pub run flutter_launcher_icons:main
# flutter pub run flutter_native_splash:create
